language: node_js
sudo: required
node_js:
  - "lts/*"
script:
  - yarn && yarn build && cd public
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
  local-dir: public